/* tslint:disable */
/* eslint-disable */
/**
 * Trade Nexus Platform API
 * Canonical public API contract for Trade Nexus.  Rules: - This file is the source of truth for external consumers. - Lona and execution engines are internal provider integrations behind adapters. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  MarketScanRequest,
  MarketScanResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    MarketScanRequestFromJSON,
    MarketScanRequestToJSON,
    MarketScanResponseFromJSON,
    MarketScanResponseToJSON,
} from '../models/index';

export interface PostMarketScanV1Request {
    marketScanRequest: MarketScanRequest;
    xRequestId?: string;
}

/**
 * ResearchApi - interface
 * 
 * @export
 * @interface ResearchApiInterface
 */
export interface ResearchApiInterface {
    /**
     * 
     * @summary Analyze market conditions and return strategy ideas
     * @param {MarketScanRequest} marketScanRequest 
     * @param {string} [xRequestId] Caller-provided request id for trace correlation.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResearchApiInterface
     */
    postMarketScanV1Raw(requestParameters: PostMarketScanV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarketScanResponse>>;

    /**
     * Analyze market conditions and return strategy ideas
     */
    postMarketScanV1(requestParameters: PostMarketScanV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarketScanResponse>;

}

/**
 * 
 */
export class ResearchApi extends runtime.BaseAPI implements ResearchApiInterface {

    /**
     * Analyze market conditions and return strategy ideas
     */
    async postMarketScanV1Raw(requestParameters: PostMarketScanV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarketScanResponse>> {
        if (requestParameters['marketScanRequest'] == null) {
            throw new runtime.RequiredError(
                'marketScanRequest',
                'Required parameter "marketScanRequest" was null or undefined when calling postMarketScanV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/research/market-scan`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MarketScanRequestToJSON(requestParameters['marketScanRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarketScanResponseFromJSON(jsonValue));
    }

    /**
     * Analyze market conditions and return strategy ideas
     */
    async postMarketScanV1(requestParameters: PostMarketScanV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarketScanResponse> {
        const response = await this.postMarketScanV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
