/* tslint:disable */
/* eslint-disable */
/**
 * Trade Nexus Platform API
 * Canonical public API contract for Trade Nexus.  Rules: - This file is the source of truth for external consumers. - Lona and execution engines are internal provider integrations behind adapters. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ValidationDecision,
  ValidationRunStatus,
  ValidationSharePermission,
  ValidationSharedRunListResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ValidationDecisionFromJSON,
    ValidationDecisionToJSON,
    ValidationRunStatusFromJSON,
    ValidationRunStatusToJSON,
    ValidationSharePermissionFromJSON,
    ValidationSharePermissionToJSON,
    ValidationSharedRunListResponseFromJSON,
    ValidationSharedRunListResponseToJSON,
} from '../models/index';

export interface ListValidationRunsSharedWithMeV2Request {
    xRequestId?: string;
    status?: ValidationRunStatus;
    finalDecision?: ValidationDecision;
    permission?: ValidationSharePermission;
    cursor?: string;
    limit?: number;
}

/**
 * SharedValidationApi - interface
 * 
 * @export
 * @interface SharedValidationApiInterface
 */
export interface SharedValidationApiInterface {
    /**
     * 
     * @summary List validation runs shared with authenticated user identity
     * @param {string} [xRequestId] Caller-provided request id for trace correlation.
     * @param {ValidationRunStatus} [status] 
     * @param {ValidationDecision} [finalDecision] 
     * @param {ValidationSharePermission} [permission] 
     * @param {string} [cursor] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SharedValidationApiInterface
     */
    listValidationRunsSharedWithMeV2Raw(requestParameters: ListValidationRunsSharedWithMeV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationSharedRunListResponse>>;

    /**
     * List validation runs shared with authenticated user identity
     */
    listValidationRunsSharedWithMeV2(requestParameters: ListValidationRunsSharedWithMeV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationSharedRunListResponse>;

}

/**
 * 
 */
export class SharedValidationApi extends runtime.BaseAPI implements SharedValidationApiInterface {

    /**
     * List validation runs shared with authenticated user identity
     */
    async listValidationRunsSharedWithMeV2Raw(requestParameters: ListValidationRunsSharedWithMeV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationSharedRunListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['finalDecision'] != null) {
            queryParameters['finalDecision'] = requestParameters['finalDecision'];
        }

        if (requestParameters['permission'] != null) {
            queryParameters['permission'] = requestParameters['permission'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/validation-sharing/runs/shared-with-me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidationSharedRunListResponseFromJSON(jsonValue));
    }

    /**
     * List validation runs shared with authenticated user identity
     */
    async listValidationRunsSharedWithMeV2(requestParameters: ListValidationRunsSharedWithMeV2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationSharedRunListResponse> {
        const response = await this.listValidationRunsSharedWithMeV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
