/* tslint:disable */
/* eslint-disable */
/**
 * Trade Nexus Platform API
 * Canonical public API contract for Trade Nexus.  Rules: - This file is the source of truth for external consumers. - Lona and execution engines are internal provider integrations behind adapters. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateValidationBaselineRequest,
  CreateValidationRegressionReplayRequest,
  CreateValidationRenderRequest,
  CreateValidationRunRequest,
  CreateValidationRunReviewRequest,
  ErrorResponse,
  ValidationArtifactResponse,
  ValidationBaselineResponse,
  ValidationRegressionReplayResponse,
  ValidationRenderResponse,
  ValidationRunResponse,
  ValidationRunReviewResponse,
} from '../models/index';
import {
    CreateValidationBaselineRequestFromJSON,
    CreateValidationBaselineRequestToJSON,
    CreateValidationRegressionReplayRequestFromJSON,
    CreateValidationRegressionReplayRequestToJSON,
    CreateValidationRenderRequestFromJSON,
    CreateValidationRenderRequestToJSON,
    CreateValidationRunRequestFromJSON,
    CreateValidationRunRequestToJSON,
    CreateValidationRunReviewRequestFromJSON,
    CreateValidationRunReviewRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ValidationArtifactResponseFromJSON,
    ValidationArtifactResponseToJSON,
    ValidationBaselineResponseFromJSON,
    ValidationBaselineResponseToJSON,
    ValidationRegressionReplayResponseFromJSON,
    ValidationRegressionReplayResponseToJSON,
    ValidationRenderResponseFromJSON,
    ValidationRenderResponseToJSON,
    ValidationRunResponseFromJSON,
    ValidationRunResponseToJSON,
    ValidationRunReviewResponseFromJSON,
    ValidationRunReviewResponseToJSON,
} from '../models/index';

export interface CreateValidationBaselineV2Request {
    createValidationBaselineRequest: CreateValidationBaselineRequest;
    xRequestId?: string;
}

export interface CreateValidationRunRenderV2Request {
    runId: string;
    createValidationRenderRequest: CreateValidationRenderRequest;
    xRequestId?: string;
}

export interface CreateValidationRunV2Request {
    createValidationRunRequest: CreateValidationRunRequest;
    xRequestId?: string;
}

export interface GetValidationRunArtifactV2Request {
    runId: string;
    xRequestId?: string;
}

export interface GetValidationRunV2Request {
    runId: string;
    xRequestId?: string;
}

export interface ReplayValidationRegressionV2Request {
    createValidationRegressionReplayRequest: CreateValidationRegressionReplayRequest;
    xRequestId?: string;
}

export interface SubmitValidationRunReviewV2Request {
    runId: string;
    createValidationRunReviewRequest: CreateValidationRunReviewRequest;
    xRequestId?: string;
}

/**
 * ValidationApi - interface
 * 
 * @export
 * @interface ValidationApiInterface
 */
export interface ValidationApiInterface {
    /**
     * 
     * @summary Promote validation run as baseline
     * @param {CreateValidationBaselineRequest} createValidationBaselineRequest 
     * @param {string} [xRequestId] Caller-provided request id for trace correlation.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApiInterface
     */
    createValidationBaselineV2Raw(requestParameters: CreateValidationBaselineV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationBaselineResponse>>;

    /**
     * Promote validation run as baseline
     */
    createValidationBaselineV2(requestParameters: CreateValidationBaselineV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationBaselineResponse>;

    /**
     * 
     * @summary Create optional html/pdf validation render artifact
     * @param {string} runId 
     * @param {CreateValidationRenderRequest} createValidationRenderRequest 
     * @param {string} [xRequestId] Caller-provided request id for trace correlation.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApiInterface
     */
    createValidationRunRenderV2Raw(requestParameters: CreateValidationRunRenderV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationRenderResponse>>;

    /**
     * Create optional html/pdf validation render artifact
     */
    createValidationRunRenderV2(requestParameters: CreateValidationRunRenderV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationRenderResponse>;

    /**
     * 
     * @summary Start validation run for strategy artifacts
     * @param {CreateValidationRunRequest} createValidationRunRequest 
     * @param {string} [xRequestId] Caller-provided request id for trace correlation.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApiInterface
     */
    createValidationRunV2Raw(requestParameters: CreateValidationRunV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationRunResponse>>;

    /**
     * Start validation run for strategy artifacts
     */
    createValidationRunV2(requestParameters: CreateValidationRunV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationRunResponse>;

    /**
     * 
     * @summary Get validation artifact payload
     * @param {string} runId 
     * @param {string} [xRequestId] Caller-provided request id for trace correlation.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApiInterface
     */
    getValidationRunArtifactV2Raw(requestParameters: GetValidationRunArtifactV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationArtifactResponse>>;

    /**
     * Get validation artifact payload
     */
    getValidationRunArtifactV2(requestParameters: GetValidationRunArtifactV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationArtifactResponse>;

    /**
     * 
     * @summary Get validation run status
     * @param {string} runId 
     * @param {string} [xRequestId] Caller-provided request id for trace correlation.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApiInterface
     */
    getValidationRunV2Raw(requestParameters: GetValidationRunV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationRunResponse>>;

    /**
     * Get validation run status
     */
    getValidationRunV2(requestParameters: GetValidationRunV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationRunResponse>;

    /**
     * 
     * @summary Replay validation regression against stored baseline
     * @param {CreateValidationRegressionReplayRequest} createValidationRegressionReplayRequest 
     * @param {string} [xRequestId] Caller-provided request id for trace correlation.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApiInterface
     */
    replayValidationRegressionV2Raw(requestParameters: ReplayValidationRegressionV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationRegressionReplayResponse>>;

    /**
     * Replay validation regression against stored baseline
     */
    replayValidationRegressionV2(requestParameters: ReplayValidationRegressionV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationRegressionReplayResponse>;

    /**
     * 
     * @summary Submit validation review decision
     * @param {string} runId 
     * @param {CreateValidationRunReviewRequest} createValidationRunReviewRequest 
     * @param {string} [xRequestId] Caller-provided request id for trace correlation.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApiInterface
     */
    submitValidationRunReviewV2Raw(requestParameters: SubmitValidationRunReviewV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationRunReviewResponse>>;

    /**
     * Submit validation review decision
     */
    submitValidationRunReviewV2(requestParameters: SubmitValidationRunReviewV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationRunReviewResponse>;

}

/**
 * 
 */
export class ValidationApi extends runtime.BaseAPI implements ValidationApiInterface {

    /**
     * Promote validation run as baseline
     */
    async createValidationBaselineV2Raw(requestParameters: CreateValidationBaselineV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationBaselineResponse>> {
        if (requestParameters['createValidationBaselineRequest'] == null) {
            throw new runtime.RequiredError(
                'createValidationBaselineRequest',
                'Required parameter "createValidationBaselineRequest" was null or undefined when calling createValidationBaselineV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/validation-baselines`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateValidationBaselineRequestToJSON(requestParameters['createValidationBaselineRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidationBaselineResponseFromJSON(jsonValue));
    }

    /**
     * Promote validation run as baseline
     */
    async createValidationBaselineV2(requestParameters: CreateValidationBaselineV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationBaselineResponse> {
        const response = await this.createValidationBaselineV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create optional html/pdf validation render artifact
     */
    async createValidationRunRenderV2Raw(requestParameters: CreateValidationRunRenderV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationRenderResponse>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling createValidationRunRenderV2().'
            );
        }

        if (requestParameters['createValidationRenderRequest'] == null) {
            throw new runtime.RequiredError(
                'createValidationRenderRequest',
                'Required parameter "createValidationRenderRequest" was null or undefined when calling createValidationRunRenderV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/validation-runs/{runId}/render`;
        urlPath = urlPath.replace(`{${"runId"}}`, encodeURIComponent(String(requestParameters['runId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateValidationRenderRequestToJSON(requestParameters['createValidationRenderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidationRenderResponseFromJSON(jsonValue));
    }

    /**
     * Create optional html/pdf validation render artifact
     */
    async createValidationRunRenderV2(requestParameters: CreateValidationRunRenderV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationRenderResponse> {
        const response = await this.createValidationRunRenderV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start validation run for strategy artifacts
     */
    async createValidationRunV2Raw(requestParameters: CreateValidationRunV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationRunResponse>> {
        if (requestParameters['createValidationRunRequest'] == null) {
            throw new runtime.RequiredError(
                'createValidationRunRequest',
                'Required parameter "createValidationRunRequest" was null or undefined when calling createValidationRunV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/validation-runs`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateValidationRunRequestToJSON(requestParameters['createValidationRunRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidationRunResponseFromJSON(jsonValue));
    }

    /**
     * Start validation run for strategy artifacts
     */
    async createValidationRunV2(requestParameters: CreateValidationRunV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationRunResponse> {
        const response = await this.createValidationRunV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get validation artifact payload
     */
    async getValidationRunArtifactV2Raw(requestParameters: GetValidationRunArtifactV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationArtifactResponse>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling getValidationRunArtifactV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/validation-runs/{runId}/artifact`;
        urlPath = urlPath.replace(`{${"runId"}}`, encodeURIComponent(String(requestParameters['runId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidationArtifactResponseFromJSON(jsonValue));
    }

    /**
     * Get validation artifact payload
     */
    async getValidationRunArtifactV2(requestParameters: GetValidationRunArtifactV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationArtifactResponse> {
        const response = await this.getValidationRunArtifactV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get validation run status
     */
    async getValidationRunV2Raw(requestParameters: GetValidationRunV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationRunResponse>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling getValidationRunV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/validation-runs/{runId}`;
        urlPath = urlPath.replace(`{${"runId"}}`, encodeURIComponent(String(requestParameters['runId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidationRunResponseFromJSON(jsonValue));
    }

    /**
     * Get validation run status
     */
    async getValidationRunV2(requestParameters: GetValidationRunV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationRunResponse> {
        const response = await this.getValidationRunV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replay validation regression against stored baseline
     */
    async replayValidationRegressionV2Raw(requestParameters: ReplayValidationRegressionV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationRegressionReplayResponse>> {
        if (requestParameters['createValidationRegressionReplayRequest'] == null) {
            throw new runtime.RequiredError(
                'createValidationRegressionReplayRequest',
                'Required parameter "createValidationRegressionReplayRequest" was null or undefined when calling replayValidationRegressionV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/validation-regressions/replay`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateValidationRegressionReplayRequestToJSON(requestParameters['createValidationRegressionReplayRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidationRegressionReplayResponseFromJSON(jsonValue));
    }

    /**
     * Replay validation regression against stored baseline
     */
    async replayValidationRegressionV2(requestParameters: ReplayValidationRegressionV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationRegressionReplayResponse> {
        const response = await this.replayValidationRegressionV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit validation review decision
     */
    async submitValidationRunReviewV2Raw(requestParameters: SubmitValidationRunReviewV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationRunReviewResponse>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling submitValidationRunReviewV2().'
            );
        }

        if (requestParameters['createValidationRunReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'createValidationRunReviewRequest',
                'Required parameter "createValidationRunReviewRequest" was null or undefined when calling submitValidationRunReviewV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/validation-runs/{runId}/review`;
        urlPath = urlPath.replace(`{${"runId"}}`, encodeURIComponent(String(requestParameters['runId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateValidationRunReviewRequestToJSON(requestParameters['createValidationRunReviewRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidationRunReviewResponseFromJSON(jsonValue));
    }

    /**
     * Submit validation review decision
     */
    async submitValidationRunReviewV2(requestParameters: SubmitValidationRunReviewV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationRunReviewResponse> {
        const response = await this.submitValidationRunReviewV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
