/* tslint:disable */
/* eslint-disable */
/**
 * Trade Nexus Platform API
 * Canonical public API contract for Trade Nexus.  Rules: - This file is the source of truth for external consumers. - Lona and execution engines are internal provider integrations behind adapters. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationRegressionReplay
 */
export interface ValidationRegressionReplay {
    /**
     * 
     * @type {string}
     * @memberof ValidationRegressionReplay
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationRegressionReplay
     */
    baselineId: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationRegressionReplay
     */
    candidateRunId: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationRegressionReplay
     */
    status: ValidationRegressionReplayStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ValidationRegressionReplay
     */
    decision: ValidationRegressionReplayDecisionEnum;
    /**
     * 
     * @type {string}
     * @memberof ValidationRegressionReplay
     */
    summary?: string;
}

/**
* @export
* @enum {string}
*/
export enum ValidationRegressionReplayStatusEnum {
    Queued = 'queued',
    Running = 'running',
    Completed = 'completed',
    Failed = 'failed'
}
/**
* @export
* @enum {string}
*/
export enum ValidationRegressionReplayDecisionEnum {
    Pass = 'pass',
    ConditionalPass = 'conditional_pass',
    Fail = 'fail',
    Unknown = 'unknown'
}


/**
 * Check if a given object implements the ValidationRegressionReplay interface.
 */
export function instanceOfValidationRegressionReplay(value: object): value is ValidationRegressionReplay {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('baselineId' in value) || value['baselineId'] === undefined) return false;
    if (!('candidateRunId' in value) || value['candidateRunId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('decision' in value) || value['decision'] === undefined) return false;
    return true;
}

export function ValidationRegressionReplayFromJSON(json: any): ValidationRegressionReplay {
    return ValidationRegressionReplayFromJSONTyped(json, false);
}

export function ValidationRegressionReplayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationRegressionReplay {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'baselineId': json['baselineId'],
        'candidateRunId': json['candidateRunId'],
        'status': json['status'],
        'decision': json['decision'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function ValidationRegressionReplayToJSON(json: any): ValidationRegressionReplay {
    return ValidationRegressionReplayToJSONTyped(json, false);
}

export function ValidationRegressionReplayToJSONTyped(value?: ValidationRegressionReplay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'baselineId': value['baselineId'],
        'candidateRunId': value['candidateRunId'],
        'status': value['status'],
        'decision': value['decision'],
        'summary': value['summary'],
    };
}

