/* tslint:disable */
/* eslint-disable */
/**
 * Trade Nexus Platform API
 * Canonical public API contract for Trade Nexus.  Rules: - This file is the source of truth for external consumers. - Lona and execution engines are internal provider integrations behind adapters. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationActorType } from './ValidationActorType';
import {
    ValidationActorTypeFromJSON,
    ValidationActorTypeFromJSONTyped,
    ValidationActorTypeToJSON,
    ValidationActorTypeToJSONTyped,
} from './ValidationActorType';

/**
 * 
 * @export
 * @interface ValidationRunActorMetadata
 */
export interface ValidationRunActorMetadata {
    /**
     * 
     * @type {ValidationActorType}
     * @memberof ValidationRunActorMetadata
     */
    actorType: ValidationActorType;
    /**
     * Canonical actor identifier for ownership/audit linkage.
     * @type {string}
     * @memberof ValidationRunActorMetadata
     */
    actorId: string;
    /**
     * Present when actorType is `user`; omitted otherwise.
     * @type {string}
     * @memberof ValidationRunActorMetadata
     */
    userId?: string | null;
    /**
     * Present when actorType is `bot`; omitted otherwise.
     * @type {string}
     * @memberof ValidationRunActorMetadata
     */
    botId?: string | null;
    /**
     * Must include `ownerUserId` for ownership auditability.
     * @type {{ [key: string]: any; }}
     * @memberof ValidationRunActorMetadata
     */
    metadata: { [key: string]: any; };
}



/**
 * Check if a given object implements the ValidationRunActorMetadata interface.
 */
export function instanceOfValidationRunActorMetadata(value: object): value is ValidationRunActorMetadata {
    if (!('actorType' in value) || value['actorType'] === undefined) return false;
    if (!('actorId' in value) || value['actorId'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function ValidationRunActorMetadataFromJSON(json: any): ValidationRunActorMetadata {
    return ValidationRunActorMetadataFromJSONTyped(json, false);
}

export function ValidationRunActorMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationRunActorMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'actorType': ValidationActorTypeFromJSON(json['actorType']),
        'actorId': json['actorId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'botId': json['botId'] == null ? undefined : json['botId'],
        'metadata': json['metadata'],
    };
}

export function ValidationRunActorMetadataToJSON(json: any): ValidationRunActorMetadata {
    return ValidationRunActorMetadataToJSONTyped(json, false);
}

export function ValidationRunActorMetadataToJSONTyped(value?: ValidationRunActorMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actorType': ValidationActorTypeToJSON(value['actorType']),
        'actorId': value['actorId'],
        'userId': value['userId'],
        'botId': value['botId'],
        'metadata': value['metadata'],
    };
}

