"""Contract tests for OC-02 OpenClaw client integration."""

from __future__ import annotations

import asyncio
import json

import httpx

from src.platform_api.clients.openclaw_client import OpenClawClient, OpenClawClientConfig


def test_openclaw_client_calls_platform_api_contracts_only() -> None:
    async def _run() -> None:
        called_paths: list[str] = []
        called_hosts: list[str] = []

        def _response_for(request: httpx.Request) -> httpx.Response:
            called_paths.append(request.url.path)
            called_hosts.append(request.url.host or "")
            assert request.url.host == "platform.local"
            assert request.url.path.startswith("/v1/") or request.url.path.startswith("/v2/")
            assert "X-Request-Id" in request.headers

            if request.url.path == "/v2/conversations/sessions":
                payload = json.loads(request.content.decode("utf-8"))
                assert payload["channel"] == "openclaw"
                return httpx.Response(201, json={"session": {"id": "conv-0001"}})
            if request.url.path == "/v2/conversations/sessions/conv-0001/turns":
                return httpx.Response(201, json={"turn": {"id": "turn-0001"}})
            if request.url.path == "/v1/research/market-scan":
                return httpx.Response(200, json={"requestId": "req-openclaw", "strategyIdeas": []})
            if request.url.path == "/v1/strategies":
                return httpx.Response(201, json={"strategy": {"id": "strat-oc-001"}})
            if request.url.path == "/v1/strategies/strat-oc-001/backtests":
                return httpx.Response(202, json={"backtest": {"id": "bt-oc-001"}})
            if request.url.path == "/v1/deployments":
                assert request.headers.get("Idempotency-Key") == "idem-oc-deploy-001"
                return httpx.Response(202, json={"deployment": {"id": "dep-oc-001"}})
            if request.url.path == "/v1/orders":
                assert request.headers.get("Idempotency-Key") == "idem-oc-order-001"
                return httpx.Response(201, json={"order": {"id": "ord-oc-001"}})
            return httpx.Response(404, json={"error": {"code": "NOT_FOUND"}})

        transport = httpx.MockTransport(_response_for)
        async with httpx.AsyncClient(base_url="https://platform.local", transport=transport) as http_client:
            client = OpenClawClient(
                config=OpenClawClientConfig(base_url="https://platform.local"),
                http_client=http_client,
            )

            session = await client.create_conversation_session(
                topic="openclaw flow",
                metadata={"notificationsOptIn": True},
            )
            session_id = session["session"]["id"]
            assert session_id == "conv-0001"

            await client.create_conversation_turn(
                session_id=session_id,
                message="deploy strategy",
            )
            await client.market_scan(asset_classes=["crypto"], capital=25_000)
            strategy = await client.create_strategy(name="OpenClaw Strategy", description="Generated by OpenClaw")
            strategy_id = strategy["strategy"]["id"]
            await client.run_backtest(
                strategy_id=strategy_id,
                data_ids=["dataset-btc-1h-2025"],
                start_date="2025-01-01",
                end_date="2025-12-31",
                initial_cash=100_000,
            )
            await client.create_deployment(
                strategy_id=strategy_id,
                mode="paper",
                capital=20_000,
                idempotency_key="idem-oc-deploy-001",
            )
            await client.place_order(
                symbol="BTCUSDT",
                side="buy",
                order_type="limit",
                quantity=0.1,
                price=64_000,
                deployment_id="dep-oc-001",
                idempotency_key="idem-oc-order-001",
            )

        expected = [
            "/v2/conversations/sessions",
            "/v2/conversations/sessions/conv-0001/turns",
            "/v1/research/market-scan",
            "/v1/strategies",
            "/v1/strategies/strat-oc-001/backtests",
            "/v1/deployments",
            "/v1/orders",
        ]
        assert called_paths == expected
        assert set(called_hosts) == {"platform.local"}

    asyncio.run(_run())
