"""End-to-end OpenClaw flow tests (OC-03)."""

from __future__ import annotations

import asyncio

import httpx

from src.main import app
from src.platform_api.clients.openclaw_client import OpenClawClient, OpenClawClientConfig


def test_openclaw_e2e_research_to_execution_flow() -> None:
    async def _run() -> None:
        transport = httpx.ASGITransport(app=app)
        async with httpx.AsyncClient(base_url="http://testserver", transport=transport) as http_client:
            client = OpenClawClient(
                config=OpenClawClientConfig(base_url="http://testserver"),
                http_client=http_client,
            )

            session = await client.create_conversation_session(
                topic="OpenClaw E2E",
                metadata={"notificationsOptIn": True},
            )
            session_id = session["session"]["id"]
            turn = await client.create_conversation_turn(
                session_id=session_id,
                message="scan markets, backtest, and deploy with risk checks",
            )
            assert turn["sessionId"] == session_id

            market_scan = await client.market_scan(asset_classes=["crypto"], capital=25_000)
            assert "strategyIdeas" in market_scan

            strategy = await client.create_strategy(
                name="OpenClaw E2E Strategy",
                description="Generated by OpenClaw e2e test.",
            )
            strategy_id = strategy["strategy"]["id"]

            backtest = await client.run_backtest(
                strategy_id=strategy_id,
                data_ids=["dataset-btc-1h-2025"],
                start_date="2025-01-01",
                end_date="2025-12-31",
                initial_cash=100_000,
            )
            backtest_id = backtest["backtest"]["id"]
            backtest_snapshot = await client.get_backtest(backtest_id=backtest_id)
            assert backtest_snapshot["backtest"]["id"] == backtest_id

            deployment = await client.create_deployment(
                strategy_id=strategy_id,
                mode="paper",
                capital=20_000,
                idempotency_key="idem-openclaw-e2e-dep-001",
            )
            deployment_id = deployment["deployment"]["id"]
            deployment_snapshot = await client.get_deployment(deployment_id=deployment_id)
            assert deployment_snapshot["deployment"]["id"] == deployment_id

            order = await client.place_order(
                symbol="BTCUSDT",
                side="buy",
                order_type="limit",
                quantity=0.05,
                price=64_000,
                deployment_id=deployment_id,
                idempotency_key="idem-openclaw-e2e-order-001",
            )
            order_id = order["order"]["id"]
            order_snapshot = await client.get_order(order_id=order_id)
            assert order_snapshot["order"]["id"] == order_id

            portfolios = await client.list_portfolios()
            assert len(portfolios["items"]) >= 1
            portfolio_id = portfolios["items"][0]["id"]
            portfolio = await client.get_portfolio(portfolio_id=portfolio_id)
            assert portfolio["portfolio"]["id"] == portfolio_id

    asyncio.run(_run())
